name: Fresh GraphQL CI
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Chrckout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello World!"

      - name: Run a multiline script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."


