name: Fresh GraphQL CI
on: [push]
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello World!"

      - name: Run a multiline script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
