name: Fresh GraphQL CI
on:
  pull_request:
    branches: [ dev]
  push:
    branches:
      -dev
jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo HEllo World!
      - name: Run a multiline script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


